/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ChatClient {
    }
}
declare global {
    interface HTMLChatClientElement extends Components.ChatClient, HTMLStencilElement {
    }
    var HTMLChatClientElement: {
        prototype: HTMLChatClientElement;
        new (): HTMLChatClientElement;
    };
    interface HTMLElementTagNameMap {
        "chat-client": HTMLChatClientElement;
    }
}
declare namespace LocalJSX {
    interface ChatClient {
    }
    interface IntrinsicElements {
        "chat-client": ChatClient;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "chat-client": LocalJSX.ChatClient & JSXBase.HTMLAttributes<HTMLChatClientElement>;
        }
    }
}
